ClassProject/ClassProject/Controllers/InstructorController.cs
using AutoMapper;
using ClassProject.Models;
using FCTDataModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClassProject.Controllers
{
	public class InstructorController : BaseController
	{
		//
		// GET: /Instructor/
		[HttpGet]
		public ActionResult Index()
		{
			using (DeptManager)
			{
				var disp = new vmInstructorSearch();
				disp.Departments = DeptManager.GetAllDepartments().ToList();
				return View(disp);
			}
		}

		[HttpPost]
		public ActionResult Index(vmInstructorSearch vm)
		{
			List<InstructorDetail> toreturn = new List<InstructorDetail>();
			IEnumerable<InstructorDetail> instructors = null;
			using (InstManager)
			{
				instructors = InstManager.GetAllTextbookDetails();
				if (vm.SelectedDept > 0)
				{
					instructors = instructors.Where(inst => inst.DepartmentID == vm.SelectedDept);
				}
				if (!string.IsNullOrEmpty(vm.SearchText))
				{
					instructors = instructors.Where(inst => inst.FullName.Contains(vm.SearchText));
				}

				JsonResult ret = Json(instructors.ToList());
				return ret;
			}
		}

		//
		// GET: /Instructor/Details/5
		[HttpGet]
		public ActionResult Details(int id)
		{
			using (DeptManager)
			{
				using (InstManager)
				{
					using (PeopleManager)
					{
						using (TBManager)
						{
							var item = InstManager.GetInstructorbyID(id);
							var disp = Mapper.Map<vmInstructor>(item);
							if (disp != null)
							{
								disp.Person = Mapper.Map<vmPerson>(PeopleManager.GetPersonbyID(item.PersonID));
								disp.Department = Mapper.Map<vmDepartment>(DeptManager.GetDepartmentbyID(item.DepartmentID));
								disp.Textbooks = TBManager.GetAllTextbooks().ToList();
								var books = InstManager.FindInstructorBooks(i => i.InstructorID == id).Select(i => i.TextBookID);
								foreach (var b in books)
								{
									var t = TBManager.GetTextbookbyID(b);
									if (t != null)
									{
										disp.InstructorTextbooks.Add(Mapper.Map<vmTextbook>(t));
									}
								}
							}
							else
							{
								disp = new vmInstructor();
								ModelState.AddModelError("", "Failed to load details for requested item.");
							}
							return View(disp);
						}
					}
				}
			}
		}

		[HttpPost]
		public ActionResult CheckOut(FormCollection c)
		{
			using (InstManager)
			{
				var item = new InstructorBook();
				item.InstructorID = Convert.ToInt32(c[0]);
				item.TextBookID = Convert.ToInt32(c[1]);
				var success = InstManager.AddInstructorBook(item);
				if (!success)
				{
					ModelState.AddModelError("", "Unable to checkout textbook. Please try again.");
				}
				return RedirectToAction("Details", new { id = item.InstructorID });
			}
		}

		[HttpPost]
		public ActionResult CheckIn(FormCollection c)
		{
			using (InstManager)
			{
				var item = InstManager.FindInstructorBooks(b => b.InstructorID == Convert.ToInt32(c[1]) && b.TextBookID == Convert.ToInt32(c[0])).FirstOrDefault();
				if (item != null)
				{
					var success = InstManager.RemoveInstructorBook(item);
					if (!success)
					{
						ModelState.AddModelError("", "Unable to check in textbook. Try again.");
					}
				}
				return RedirectToAction("Details", new { id = Convert.ToInt32(c[1]) });
			}
		}

		//
		// GET: /Instructor/Create
		[HttpGet]
		public ActionResult Create()
		{
			using (DeptManager)
			{
				var disp = new vmInstructor();
				disp.Departments = DeptManager.GetAllDepartments().OrderBy(d => d.Name).ToList();
				return View(disp);
			}
		}
		//
		// POST: /Instructor/Create
		[HttpPost]
		public ActionResult Create(vmInstructor inst)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (InstManager)
					{
						using (PeopleManager)
						{
							var person = Mapper.Map<Person>(inst.Person);
							var success = PeopleManager.AddPerson(person);
							if (success)
							{
								var item = Mapper.Map<Instructor>(inst);
								item.PersonID = person.ID;
								success = InstManager.AddInstructor(item);
								if (success)
								{
									return RedirectToAction("Details", new { id = item.ID });
								}
								else
								{
									throw new DataException("Unable to save Instructor. Please try again.");
								}
							}
							else
							{
								throw new DataException("Unable to save person. Please try again.");
							}
						}
					}
				}
			}
			catch (DataException ex)
			{
				ModelState.AddModelError("", ex.Message);
			}
			using (DeptManager)
			{
				inst.Departments = DeptManager.GetAllDepartments().OrderBy(d => d.Name).ToList();
			}
			return View(inst);
		}

		//
		// GET: /Instructor/Edit/5
		[HttpGet]
		public ActionResult Edit(int id)
		{
			using (DeptManager)
			{
				using (InstManager)
				{
					using (PeopleManager)
					{
						var item = InstManager.GetInstructorbyID(id);
						var disp = Mapper.Map<vmInstructor>(item);
						if (disp != null)
						{
							disp.Person = Mapper.Map<vmPerson>(PeopleManager.GetPersonbyID(item.PersonID));
							disp.Departments = DeptManager.GetAllDepartments().OrderBy(d => d.Name).ToList();
						}
						else
						{
							disp = new vmInstructor();
							ModelState.AddModelError("", "Failed to load details fo requested item.");
						}
						return View(disp);
					}
				}
			}
		}
		//
		// POST: /Instructor/Edit/5
		[HttpPost]
		public ActionResult Edit(vmInstructor inst)
		{
			try
			{
				if (ModelState.IsValid)
				{
					using (InstManager)
					{
						using (PeopleManager)
						{
							var person = PeopleManager.GetPersonbyID(inst.PersonID);
							person.FirstMidName = inst.Person.FirstMidName;
							person.LastName = inst.Person.LastName;
							var success = PeopleManager.UpdatePerson(person);
							if (success)
							{
								var item = InstManager.GetInstructorbyID(inst.ID);
								item.PersonID = person.ID;
								item.HireDate = inst.HireDate;
								item.DepartmentID = inst.DepartmentID;
								success = InstManager.UpdateInstructor(item);
								if (success)
								{
									return RedirectToAction("Details", new { id = item.ID });
								}
								else
								{
									throw new DataException("Unable to save Instructor. Please try again.");
								}
							}
							else
							{
								throw new DataException("Unable to save person. Please try again.");
							}
						}
					}
				}
			}
			catch (DataException ex)
			{
				ModelState.AddModelError("", ex.Message);
			}
			using (DeptManager)
			{
				inst.Departments = DeptManager.GetAllDepartments().OrderBy(d => d.Name).ToList();
			}
			return View(inst);
		}

		//
		// GET: /Instructor/Delete/5

		public ActionResult Delete(int id)
		{
			using (DeptManager)
			{
				using (InstManager)
				{
					using (PeopleManager)
					{
						var item = InstManager.GetInstructorbyID(id);
						var disp = Mapper.Map<vmInstructor>(item);
						if (disp != null)
						{
							disp.Person = Mapper.Map<vmPerson>(PeopleManager.GetPersonbyID(item.PersonID));
							disp.Department = Mapper.Map<vmDepartment>(DeptManager.GetDepartmentbyID(item.DepartmentID));
						}
						else
						{
							disp = new vmInstructor();
							ModelState.AddModelError("", "Failed to load details for requested object");
						}
						return View(disp);
					}
				}
			}
		}
		//
		// POST: /Instructor/Delete/5

		[HttpPost]
		public ActionResult Delete(vmInstructor inst)
		{
			try
			{
				using (InstManager)
				{
					var item = InstManager.GetInstructorbyID(inst.ID);
					var success = InstManager.RemoveInstructor(item);
					if (success)
					{
						return RedirectToAction("Index");
					}
					throw new DataException("Enable to delete intructor " + inst.Person.FullName + ". Please try again.");
				}
			}
			catch (DataException ex)
			{
				ModelState.AddModelError("", ex.Message);
			}
			return View(inst);
		}
	}
}

ClassProject/ClassProject/Views/Instructor/Create.cshtml
@model ClassProject.Models.vmInstructor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Instructor</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.HireDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HireDate)
            @Html.ValidationMessageFor(model => model.HireDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Person.FirstMidName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Person.FirstMidName)
            @Html.ValidationMessageFor(model => model.Person.FirstMidName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Person.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Person.LastName)
            @Html.ValidationMessageFor(model => model.Person.LastName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Department.Name)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.DepartmentID, new SelectList(Model.Departments,"ID","Name"))
            @Html.ValidationMessageFor(model => model.DepartmentID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClassProject/ClassProject/Views/Instructor/Delete.cshtml
@model ClassProject.Models.vmInstructor

@{
    ViewBag.Title = "Delete " + Model.Person.FullName;
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm()) {
<fieldset>
    <legend>Instructor</legend>
    @Html.HiddenFor(model => model.ID)
    <div class="display-label">HireDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HireDate)
    </div>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Person.FullName)
    </div>

    <div class="display-label">Department</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Department.Name)
    </div>
</fieldset>

    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ClassProject/ClassProject/Views/Instructor/Details.cshtml
@model ClassProject.Models.vmInstructor

@{
	ViewBag.Title = Model.Person.FullName;
}

<h2>@ViewBag.Title</h2>

<div class="column">
	<fieldset>
		<legend>Details</legend>

		<div class="display-label">Hire Date</div>
		<div class="display-field">
			@Html.DisplayFor(model => model.HireDate)
		</div>

		<div class="display-label">Department</div>
		<div class="display-field">
			@Html.DisplayFor(model => model.Department.Name)
		</div>
	</fieldset>
</div>
<div class="column">
	@using (Html.BeginForm("CheckOut", "Instructor", FormMethod.Post, new { id = "out" }))
 {
		<fieldset>
			<legend>Check Out Textbook</legend>
			<div class="editor-field">
				@Html.HiddenFor(model => model.ID)
				@Html.DropDownList("books", new SelectList(Model.Textbooks, "ID", "Name"))
				<input type="submit" value="Check Out" style="float: right" />
			</div>
		</fieldset>
 }
	<fieldset>
		<legend>Currently Checked Out</legend>
		<ul>
			@foreach (var item in Model.InstructorTextbooks)
   {
	   using (Html.BeginForm("CheckIn", "Instructor", FormMethod.Post, new { id = item.ID }))
	   {
				<li class="display-field" style="list-style-type: disc">
					@Html.HiddenFor(modelItem => item.ID)
					@Html.HiddenFor(model => model.ID)
					@Html.DisplayFor(modelItem => item.Name)<input type="submit" value="Check In" style="float:right"/>
				</li>
	   }
   }
		</ul>
	</fieldset>
</div>
<p>
	@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClassProject/ClassProject/Views/Instructor/Edit.cshtml
@model ClassProject.Models.vmInstructor

@{
    ViewBag.Title = "Edit " + Model.Person.FullName;
}

<h2>@ViewBag.Title</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Details</legend>

        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.HireDate)

            @Html.HiddenFor(model => model.Person.FirstMidName)
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Person.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Person.LastName)
            @Html.ValidationMessageFor(model => model.Person.LastName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Department.Name)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.DepartmentID, new SelectList(Model.Departments,"ID","Name"))
            @Html.ValidationMessageFor(model => model.DepartmentID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClassProject/ClassProject/Views/Instructor/Index.cshtml
@model ClassProject.Models.vmInstructorSearch
@section Scripts{

	<script type="text/javascript">
		var request = new AjaxRequest();
		request.Url = "Instructor/Index";
		request.Verb = Verb.Post;

		request.OnSuccess.Add(bind);
		request.OnError.Add(error);

		function getfields() {
			$GridView("courses").Loading("Loading...");
			request.Post();
		}

		function bind(e) {
			var list = e.ResponseObject;
			$GridView("courses").Bind(e.ResponseObject);
		}
		function error() {
			$GridView("courses").Loading("An error occurred during the search.");
		}


		@*Page.OnLoad.Add(function () {
            $Button("vend").OnClick.Add(function () {
                Page.Href("@Url.Action("Create", "Vendor", "")");
            });
        }); *@      
	</script>
}
@{
    ViewBag.Title = "Instructors";
}

<h2>@ViewBag.Title</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
	<fieldset>
		<legend>Find Instructors</legend>
		<div style="display: inline-block">
			<div class="editor-label">
				Search By
			</div>
			<div class="editor-field">
				@Html.TextBoxFor(model => model.SearchText, new { @placeholder = "Instructor Name", style = "width:400px" })
			</div>
		</div>
		<div style="display: inline-block">
			<div class="editor-label">
				Department
			</div>
			<div class="editor-field">
				@Html.DropDownListFor(model => model.SelectedDept, new SelectList(Model.Departments, "ID", "Name"), "Any")
			</div>
		</div>
		<br />
		<br />
		<p style="text-align: center">
			<input id="search" type="button" onclick="getfields()" value="Search" />
		</p>
	</fieldset>
}

<table class="gridview" id="courses" width="99%">
	<thead>
		<tr>
			<th width="50" data="Instructor/Details/{ID}" display="Details" type="link"></th>
			<th width="50" data="Instructor/Edit/{ID}" display="Edit" type="link"></th>
			<th width="50" data="Instructor/Delete/{ID}" display="Delete" type="link"></th>
			
			<th data="FullName">Name</th>
			<th data="DepartmentName">Department</th>
			<th data="HireDate">Hired</th>
		</tr>
	</thead>
</table>